project 'KDXia.xcodeproj'

# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'KDXia' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KDXia
  pod 'Alamofire'
  pod 'SnapKit', '~> 0.15.0'
  target 'KDXiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
